export default [
  {
    id: "1-vendor",
    name: "prasanth studios",
    place: "chennai",
    verified: true,
    rating: "4.95",
    amount: "17,00,000",
    images: {
      0: "https://img.freepik.com/free-photo/hands-indian-bride-groom-intertwined-together-making-authentic-wedding-ritual_8353-10047.jpg?semt=ais_hybrid",
      1: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110939.jpg?semt=ais_hybrid",
      2: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110947.jpg?semt=ais_hybrid",
      3: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111013.jpg?semt=ais_hybrid",
      4: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111009.jpg?semt=ais_hybrid",
    },
  },
  {
    id: "2-vendor",
    name: "prasanth studios",
    place: "chennai",
    verified: true,
    rating: "4.95",
    amount: "17,00,000",
    images: {
      0: "https://img.freepik.com/free-photo/hands-indian-bride-groom-intertwined-together-making-authentic-wedding-ritual_8353-10047.jpg?semt=ais_hybrid",
      1: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110939.jpg?semt=ais_hybrid",
      2: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110947.jpg?semt=ais_hybrid",
      3: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111013.jpg?semt=ais_hybrid",
      4: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111009.jpg?semt=ais_hybrid",
    },
  },
  {
    id: "3-vendor",
    name: "prasanth studios",
    place: "chennai",
    verified: true,
    rating: "4.95",
    amount: "17,00,000",
    images: {
      0: "https://img.freepik.com/free-photo/hands-indian-bride-groom-intertwined-together-making-authentic-wedding-ritual_8353-10047.jpg?semt=ais_hybrid",
      1: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110939.jpg?semt=ais_hybrid",
      2: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110947.jpg?semt=ais_hybrid",
      3: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111013.jpg?semt=ais_hybrid",
      4: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111009.jpg?semt=ais_hybrid",
    },
  },
  {
    id: "4-vendor",
    name: "prasanth studios",
    place: "chennai",
    verified: true,
    rating: "4.95",
    amount: "17,00,000",
    images: {
      0: "https://img.freepik.com/free-photo/hands-indian-bride-groom-intertwined-together-making-authentic-wedding-ritual_8353-10047.jpg?semt=ais_hybrid",
      1: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110939.jpg?semt=ais_hybrid",
      2: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110947.jpg?semt=ais_hybrid",
      3: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111013.jpg?semt=ais_hybrid",
      4: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111009.jpg?semt=ais_hybrid",
    },
  },
  {
    id: "5-vendor",
    name: "prasanth studios",
    place: "chennai",
    verified: true,
    rating: "4.95",
    amount: "17,00,000",
    images: {
      0: "https://img.freepik.com/free-photo/hands-indian-bride-groom-intertwined-together-making-authentic-wedding-ritual_8353-10047.jpg?semt=ais_hybrid",
      1: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110939.jpg?semt=ais_hybrid",
      2: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110947.jpg?semt=ais_hybrid",
      3: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111013.jpg?semt=ais_hybrid",
      4: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111009.jpg?semt=ais_hybrid",
    },
  },
  {
    id: "6-vendor",
    name: "prasanth studios",
    place: "chennai",
    verified: true,
    rating: "4.95",
    amount: "17,00,000",
    images: {
      0: "https://img.freepik.com/free-photo/hands-indian-bride-groom-intertwined-together-making-authentic-wedding-ritual_8353-10047.jpg?semt=ais_hybrid",
      1: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110939.jpg?semt=ais_hybrid",
      2: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110947.jpg?semt=ais_hybrid",
      3: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111013.jpg?semt=ais_hybrid",
      4: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111009.jpg?semt=ais_hybrid",
    },
  },
  {
    id: "7-vendor",
    name: "prasanth studios",
    place: "chennai",
    verified: true,
    rating: "4.95",
    amount: "17,00,000",
    images: {
      0: "https://img.freepik.com/free-photo/hands-indian-bride-groom-intertwined-together-making-authentic-wedding-ritual_8353-10047.jpg?semt=ais_hybrid",
      1: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110939.jpg?semt=ais_hybrid",
      2: "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110947.jpg?semt=ais_hybrid",
      3: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111013.jpg?semt=ais_hybrid",
      4: "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111009.jpg?semt=ais_hybrid",
    },
  },
  {
    id: "8-vendor",
    name: "prasanth studios",
    place: "chennai",
    verified: true,
    rating: "4.95",
    amount: "17,00,000",
    images: [
      "https://img.freepik.com/free-photo/hands-indian-bride-groom-intertwined-together-making-authentic-wedding-ritual_8353-10047.jpg?semt=ais_hybrid",
      "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110939.jpg?semt=ais_hybrid",
      "https://img.freepik.com/free-photo/indian-couple-celebrating-propose-day-by-being-romantic-with-each-other_23-2151110947.jpg?semt=ais_hybrid",
      "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111013.jpg?semt=ais_hybrid",
      "https://img.freepik.com/free-photo/affectionate-indian-couple-celebrating-propose-day-together_23-2151111009.jpg?semt=ais_hybrid",
    ],
  },
];
